######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 14:21:12 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . GeneratedFiles release
INCLUDEPATH += .
QT += network

# Input
HEADERS += dataStruct.h server.h
FORMS += server.ui
SOURCES += main.cpp server.cpp
RESOURCES += server.qrc
RC_FILE = icon.rc
