######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 7 05:49:02 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . GeneratedFiles
INCLUDEPATH += .
QT += network

# Input
HEADERS += client.h dataStruct.h
FORMS += client.ui
SOURCES += client.cpp main.cpp
RESOURCES += client.qrc
RC_FILE = icon.rc
