######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 6 13:08:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gobang.h
SOURCES += gobang.cpp main.cpp
